CREATE TABLE bac_stocks7 (
`Date` DATETIME NOT NULL,
`Open` FLOAT NOT NULL,
`High` FLOAT NOT NULL,
`Low` FLOAT NOT NULL,
`Close` FLOAT NOT NULL,
`Adj Close` FLOAT NOT NULL,
`Volume` FLOAT NOT NULL,
PRIMARY KEY (`Date`));
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/BAC.csv'
INTO TABLE bac_stocks7
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


